#!/usr/bin/env python3
"""Isolated negative controls for layout/trng_digital/erc-supply-spec.json
(issue #223).  Each control mutates a COPY of the committed routed GDS (or of
the spec) in a temp directory, runs the same `klt erc --findings-only`
command as the real run, and records which ERC findings fire.  The committed
GDS/spec/erc.json are never touched.

    uv run --no-project --with klayout==0.30.12 python -I \
        layout/trng_digital/erc-negative-controls.py

Writes layout/trng_digital/erc-negative-controls.json (compact summary; the
per-control native reports are 16 MB each and are not committed -- they are
regenerated by this script, and the summary records the mutated-input and
spec hashes so a re-run is checkable).  Exit status 1 if a control does not
detect what it is designed to detect.
"""
import collections, hashlib, json, subprocess, sys, tempfile
from pathlib import Path
import klayout.db as db

ROOT = Path(__file__).resolve().parents[2]
D = ROOT / "layout" / "trng_digital"
GDS, SPEC = D / "trng_digital.gds", D / "erc-supply-spec.json"
OUT = D / "erc-negative-controls.json"
TAP, NWELL, VIA4, MET5 = (65, 44), (64, 20), (71, 44), (72, 20)


def sha(p):
    return "sha256:" + hashlib.sha256(Path(p).read_bytes()).hexdigest()


def load():
    l = db.Layout(); l.read(str(GDS)); return l, l.top_cell()


def run_klt(gds, spec, tmp, tag):
    out = tmp / f"{tag}.erc.json"
    cmd = ["klt", "erc", str(gds), str(spec), "--findings-only", "--format", "json"]
    with open(out, "w") as f:
        r = subprocess.run(cmd, stdout=f, stderr=subprocess.PIPE, text=True, cwd=ROOT)
    if r.returncode not in (0, 3, 4):
        raise SystemExit(f"klt failed rc={r.returncode}: {r.stderr[-500:]}")
    d = json.loads(out.read_text())
    return r.returncode, d


def summarize(d):
    f = d.get("erc_findings", [])
    return {
        "erc_status": d.get("erc_status"),
        "erc_finding_count": d.get("erc_finding_count"),
        "rules": dict(collections.Counter(x["rule"] for x in f)),
        "findings_sample": f[:3],
        "net_islands": {n["name"]: n["matched_islands"] for n in d.get("nets", [])},
        "coverage_checked_non_gate": [c for c in d["erc_coverage"]["checked"] if "floating_gate" not in c],
        "coverage_skipped": d["erc_coverage"]["skipped"],
    }


def tap_instances(l, top):
    """Top-cell instances of the (single) cell carrying 65/44 tap geometry."""
    tc = [c for c in l.each_cell() if not c.shapes(l.layer(*TAP)).is_empty()]
    assert len(tc) == 1, [c.name for c in tc]
    return tc[0], [i for i in top.each_inst() if i.cell_index == tc[0].cell_index()]


def variant_tapcell(l, master, drop):
    """Copy of the tapcell master with the n-tap ('n') or p-tap ('p') removed."""
    new = l.create_cell(master.name + "_NO_" + drop.upper() + "TAP")
    new.copy_shapes(master)
    tl, nl = l.layer(*TAP), l.layer(*NWELL)
    nwell = db.Region(master.shapes(nl))
    for s in list(new.shapes(tl).each()):
        inside = not (db.Region(s.polygon) & nwell).is_empty()
        if (drop == "n") == inside:
            new.shapes(tl).erase(s)
    for c in master.each_inst():
        new.insert(c)
    return new


def main():
    results, ok = [], True
    with tempfile.TemporaryDirectory() as t:
        tmp = Path(t)

        def control(cid, desc, expect_rule, mutate=None, spec=SPEC, expect_clean=False, extra=None):
            nonlocal ok
            gds = GDS
            if mutate:
                l, top = load(); mutate(l, top)
                gds = tmp / f"{cid}.gds"; l.write(str(gds))
            rc, d = run_klt(gds, spec, tmp, cid)
            s = summarize(d)
            hit = (s["erc_status"] == "clean" and s["erc_finding_count"] == 0) if expect_clean \
                else (expect_rule in s["rules"])
            ok &= hit
            results.append({"id": cid, "description": desc, "expected": "clean" if expect_clean else expect_rule,
                            "detected": hit, "klt_exit": rc, "input_sha256": sha(gds), "spec_sha256": sha(spec),
                            "command": f"klt erc <input> <spec> --findings-only --format json", **s, **(extra or {})})
            print(cid, "OK" if hit else "FAIL", s["rules"], s["net_islands"])

        control("P0-baseline", "committed GDS + committed spec (positive control: must be clean)",
                None, expect_clean=True)

        def m_via4(l, top):
            n = 0
            for c in l.each_cell():
                sh = c.shapes(l.layer(*VIA4)); n += sh.size(); sh.clear()
            assert n > 0
        control("N1-supply-disconnection", "delete every met4-met5 cut (71/44): the met5 straps (and their VPWR/VGND "
                "labels) detach from the met4/met1 grid", "erc.unconnected_net", m_via4)

        def m_short(l, top):
            li = l.layer(*MET5)
            ys = sorted({(s.bbox().bottom, s.bbox().top) for s in top.shapes(li).each() if s.bbox().width() > 100000})
            (b0, t0), (b1, t1) = ys[0], ys[1]  # two adjacent full-width straps (alternating VPWR/VGND)
            top.shapes(li).insert(db.Box(100000, t0 if t0 < b1 else t1, 101600, b1 if t0 < b1 else b0))
            top.shapes(li).insert(db.Box(100000, min(b0, b1), 101600, max(t0, t1)))
        control("N2-supply-short", "drop a met5 box bridging two adjacent power straps (one VPWR, one VGND)",
                "erc.supply_short", m_short)

        def m_ntap(l, top):
            master, insts = tap_instances(l, top)
            nl = l.layer(*NWELL)
            wells = db.Region(top.begin_shapes_rec(nl)).merged()
            per = collections.defaultdict(list)
            for i in insts:
                p = i.dtrans.disp
                pt = db.Point(round(p.x / l.dbu), round(p.y / l.dbu))
                # the instance's n-tap lies inside its row's well: find by the master's n-tap location
                tb = [s.bbox() for s in master.shapes(l.layer(*TAP)).each()]
                for b in tb:
                    bb = i.trans * b
                    for k, w in enumerate(wells.each()):
                        if w.bbox().overlaps(bb) and not (db.Region(bb) & db.Region(w)).is_empty():
                            per[k].append(i)
            k = min(per, key=lambda k: len(per[k]))
            new = variant_tapcell(l, master, "n")
            for i in per[k]:
                i.cell_index = new.cell_index()
            print("n-tap removed from", len(per[k]), "tapcell(s) of one well")
        control("N3-missing-well-tie", "remove the n-tap from every tapcell of one nwell: that drawn well keeps no "
                "VPWR tap", "erc.missing_tie", m_ntap)

        def m_ptap(l, top):
            master, insts = tap_instances(l, top)
            new = variant_tapcell(l, master, "p")
            insts[0].cell_index = new.cell_index()
        control("N4-missing-substrate-tie", "remove the p-tap from one tapcell: its asserted substrate box holds no "
                "VGND tap", "erc.missing_tie", m_ptap)

        bad = json.loads(SPEC.read_text())
        bad["ties"][0]["net"] = bad["nets"][1]["name"]
        sp = tmp / "wrongnet.spec.json"; sp.write_text(json.dumps(bad))
        control("N5-wrong-net-tie", "spec mutation: declare the nwell tie against VGND instead of VPWR (every well's "
                "taps reach VPWR, not VGND)", "erc.missing_tie", spec=sp)

    OUT.write_text(json.dumps({
        "schema_version": 1, "issue": 223, "klt_version": subprocess.run(["klt", "--version"], capture_output=True, text=True).stdout.strip(),
        "klayout_version": db.__version__ if hasattr(db, "__version__") else None,
        "all_detected": ok, "controls": results}, indent=1) + "\n")
    sys.exit(0 if ok else 1)


main()
