#!/usr/bin/env python3
"""Unit test for ``design/netlist.py``'s minimum-xschem-version gate.

    python3 design/test_netlist_xschem_version.py

Pure Python: no xschem, no PDK install, no ngspice. The real ``xschem
--version`` subprocess is the one thing stubbed out, so this runs on the
PR-blocking CI path alongside ``design/test_pdk_search.py`` rather than on
the PDK-gated nightly.

Why this exists (issue #151). sky130's device symbols carry their
device-area parameters as ``expr()`` templates over the symbol's own
``@W``/``@nf`` attributes. xschem 3.4.7 is the first release that evaluates
them at netlist time; every earlier release -- including the 3.4.4 that
``apt-get install xschem`` resolves on Debian/Ubuntu -- copies them through
verbatim, and ngspice then refuses the resulting netlist outright
(``Undefined parameter [ad]``). ``netlist.py --check`` verifies staleness
and ERC, never simulability, so it cannot catch that on its own: a netlist
regenerated by a too-old xschem diffs clean against itself and reports
green. ``check_xschem_version()`` is the guard that makes the tool refuse
first, and this file is that guard's regression fixture -- without it, the
gate could be silently weakened (a wrong comparison, a swallowed exception,
a floor that stops being read from ``design/pdk.json``) and every existing
check in this repo would still pass.

Deliberately covers the *ordering* comparison rather than only the
equal/not-equal cases: the floor is a minimum, not an equality pin -- a
newer xschem must be accepted, because a newer xschem whose output
formatting moves is meant to be caught by ``--check``'s staleness diff, not
blocked here.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import netlist  # path insert above must run before this import resolves
from _test_check import Checker

_checker = Checker()
_check = _checker.check


def _with_reported_version(version: str | None, floor: str = "3.4.7"):
    """Run ``check_xschem_version()`` with both inputs stubbed.

    Returns the :class:`netlist.ExportError` message, or ``None`` when the
    gate let the export proceed.
    """
    real_version = netlist.xschem_version
    real_floor = netlist.xschem_version_min
    netlist.xschem_version = lambda: version
    netlist.xschem_version_min = lambda: floor
    try:
        netlist.check_xschem_version()
        return None
    except netlist.ExportError as exc:
        return str(exc)
    finally:
        netlist.xschem_version = real_version
        netlist.xschem_version_min = real_floor


def test_version_tuple_orders_numerically() -> None:
    _check(
        "_version_tuple: parses a dotted release into ints",
        netlist._version_tuple("3.4.7") == (3, 4, 7),
    )
    _check(
        "_version_tuple: 3.4.4 sorts below 3.4.7 (not a string compare)",
        netlist._version_tuple("3.4.4") < netlist._version_tuple("3.4.7"),
    )
    _check(
        "_version_tuple: 3.4.10 sorts ABOVE 3.4.7 (a string compare would not)",
        netlist._version_tuple("3.4.10") > netlist._version_tuple("3.4.7"),
    )


def test_floor_rejects_the_distro_xschem() -> None:
    # 3.4.4-1 is what ubuntu-noble's `apt-get install xschem` resolves, and
    # what pdk-nightly installed for the three weeks it was silently red.
    message = _with_reported_version("3.4.4")
    _check(
        "check_xschem_version: 3.4.4 is rejected against a 3.4.7 floor",
        message is not None,
    )
    _check(
        "check_xschem_version: the rejection names both versions",
        bool(message) and "3.4.4" in message and "3.4.7" in message,
        detail=repr(message),
    )
    _check(
        "check_xschem_version: the rejection explains the expr() cause",
        bool(message) and "expr()" in message,
        detail=repr(message),
    )


def test_floor_accepts_equal_and_newer() -> None:
    _check(
        "check_xschem_version: exactly the floor is accepted",
        _with_reported_version("3.4.7") is None,
    )
    _check(
        "check_xschem_version: a NEWER xschem is accepted (minimum, not a pin)",
        _with_reported_version("3.5.0") is None,
    )
    _check(
        "check_xschem_version: 3.4.10 is accepted against a 3.4.7 floor",
        _with_reported_version("3.4.10") is None,
    )


def test_unreadable_version_is_refused_not_assumed_ok() -> None:
    # "Could not tell" must fail closed: the whole point of the gate is that
    # an unverified netlister may be producing unsimulable output.
    message = _with_reported_version(None)
    _check(
        "check_xschem_version: an unreadable version is refused, not waved through",
        message is not None,
    )
    _check(
        "check_xschem_version: the refusal says the version could not be determined",
        bool(message) and "could not determine" in message,
        detail=repr(message),
    )


def test_floor_is_read_from_committed_config() -> None:
    # The committed floor must be a real value netlist.py can order, and it
    # must come from design/pdk.json rather than only from the module
    # default -- otherwise editing pdk.json would silently do nothing.
    import json

    committed = json.loads((Path(netlist.DESIGN_DIR) / "pdk.json").read_text())
    _check(
        "design/pdk.json: carries an xschem_version_min",
        "xschem_version_min" in committed,
    )
    floor = committed.get("xschem_version_min", "")
    _check(
        "design/pdk.json: the floor parses as a dotted version",
        bool(floor) and all(part.isdigit() for part in str(floor).split(".")),
        detail=repr(floor),
    )
    _check(
        "design/pdk.json: the committed floor is at least 3.4.7 (expr() evaluation)",
        bool(floor) and netlist._version_tuple(str(floor)) >= (3, 4, 7),
        detail=repr(floor),
    )
    _check(
        "xschem_version_min(): reads the committed value, not just the default",
        netlist.xschem_version_min() == str(floor),
        detail=f"{netlist.xschem_version_min()!r} != {str(floor)!r}",
    )


def main() -> int:
    test_version_tuple_orders_numerically()
    test_floor_rejects_the_distro_xschem()
    test_floor_accepts_equal_and_newer()
    test_unreadable_version_is_refused_not_assumed_ok()
    test_floor_is_read_from_committed_config()
    return _checker.summary("design/test_netlist_xschem_version.py")


if __name__ == "__main__":
    raise SystemExit(main())
